version: '3.7'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:13.1-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - db_network
  web:
    build: .
    restart: always
    expose:
      - 8000
    volumes:
      - .:/code
      - static_volume:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - nginx_network
      - db_network
  nginx:
    image: nginx:1.19.5-alpine
    container_name: nginx
    volumes:
      - static_volume:/code/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge